// Static, compile-time string constants for client-side multi-language
// support. Each supported language exports the same set of string IDs,
// organized by screen/feature. Values that need interpolation are
// functions (e.g. `(name) => ...`) rather than plain strings.
//
// Supported languages: English (en), Spanish (es), French (fr),
// Italian (it), Portuguese (pt), Russian (ru).

export const strings = {
    en: {
        home: {
            kickedTitle: "Kicked from lobby",
            kickedDescription: "The host has removed you from the lobby.",
            hostLeftTitle: "Host has left",
            hostLeftDescription: "The host disconnected and the lobby has been closed.",
            create: "Create",
            join: "Join",
            languageLabel: "Language",
        },
        create: {
            locationDenied: 'Location access was denied. To re-enable it, go to Safari Settings → Websites → Location, find localhost, and set it to "Allow". Then reload the page.',
            locationUnavailable: "Location information is unavailable. Please try again.",
            locationTimeout: "Location request timed out. Please try again.",
            geolocationNotSupported: "Geolocation is not supported by your browser",
            title: "create",
            description: "Enter your name below to be displayed to others",
            selectAvatarTitle: "Select avatar",
            selectAvatarDescription: "Choose an avatar to be viewed by others",
            avatarOptional: "Select an avatar if you'd like...",
            nameLabel: "Name",
            namePlaceholder: "Neo",
            createButton: "create",
        },
        join: {
            title: "join",
            description: "Enter your name below to be displayed to others and the pin provided by the host",
            selectAvatarTitle: "Select avatar",
            selectAvatarDescription: "Choose an avatar to be viewed by others",
            avatarOptional: "Select an avatar if you'd like...",
            nameLabel: "Name",
            namePlaceholder: "Neo",
            pinLabel: "Pin",
            joinButton: "Join host",
            errorTitle: "Lobby not found",
            errorDescription: "The lobby code is invalid or the game has already ended. Check the code and try again.",
        },
        lobby: {
            start: "Start",
            waitingForHost: "Waiting for host to start...",
            roomPin: "ROOM PIN",
            loading: "Loading...",
            players: "PLAYERS",
            joined: "joined",
            playerFallback: "Player",
            newHostTitle: "New host",
            newHostDescription: (name) => `${name} is now the host.`,
            pinCopiedTitle: "PIN Copied",
            pinCopiedDescription: "Lobby PIN has been copied to clipboard.",
            errorTitle: "Error",
            errorCopyDescription: "Failed to copy PIN to clipboard. Try again.",
            hostBadge: "Host",
            copyPinLabel: "Copy room PIN",
            kickPlayerLabel: (name) => `Kick ${name}`,
        },
        questions: {
            newHostTitle: "New host",
            newHostDescription: (name) => `${name} is now the host.`,
            questionOf: (current, total) => `Question ${current} of ${total}`,
            watchingBanner: "👀 You are watching — voting is locked to original players",
            vote: "Vote",
            voted: "Voted",
        },
        poll: {
            1: {
                question: "What is your current top priority for your meal?",
                options: { 1: "Ambiance", 2: "Budget", 3: "Cuisine", 4: "Distance" },
            },
            2: {
                question: "What is your preferred price range?",
                options: { 1: "$", 2: "$$", 3: "$$$", 4: "$$$$" },
            },
            3: {
                question: "What type of cuisine are you in the mood for?",
                options: { 1: "Italian", 2: "Mexican", 3: "Chinese", 4: "Japanese", 5: "Mediterranean", 6: "American", 7: "French", 8: "Thai" },
            },
            4: {
                question: "How far are you willing to travel?",
                options: { 1: "Walking distance (0-1 miles)", 2: "Short drive (1-5 miles)", 3: "Moderate drive (5-15 miles)", 4: "Long drive (15+ miles)" },
            },
        },
        results: {
            radiusWalking: "Walking distance (0-1 miles)",
            radiusShortDrive: "Short drive (1-5 miles)",
            radiusModerateDrive: "Moderate drive (5-15 miles)",
            radiusLongDrive: "Long drive (15+ miles)",
            youAreHere: "You are here",
            newHostTitle: "New host",
            newHostDescription: (name) => `${name} is now the host.`,
            watching: "👀 Watching",
            broadenedSearchText: "We broadened the search area to find more options",
            broadenedSearchRadius: (label) => ` (now searching within ${label})`,
            votedSuffix: "voted",
            goingTo: "We're going to...",
            openNow: "Open now",
            closed: "Closed",
            viewOnGoogleMaps: "View on Google Maps",
            exit: "Exit",
            exitVotingPlayerMessage: "Leave the game? You'll be removed and the others will continue voting without you.",
            exitVotingHostMessage: "Leave as host? Another player will take over and voting will continue. If you're the only player, this will end the game.",
            yourVote: "✓ Your vote",
            alreadyVoted: "Already voted",
            voteForThis: "Vote for this",
            votedCheck: "✓ Voted",
            tieBreakTitle: "It's a tie!",
            tieBreakSubtitle: "Spinning to break the tie...",
            tieBreakWinnerLabel: "The choice is clear:",
        },
        leaveGuard: {
            playerLeaveMessage: "Leave the game? You'll be removed and the others will continue without you.",
            hostLeaveMessage: "Leave as host? Another player will take over and the game will continue. If you're the only player, this will end the game.",
        },
    },
    es: {
        home: {
            kickedTitle: "Expulsado del lobby",
            kickedDescription: "El anfitrión te ha eliminado del lobby.",
            hostLeftTitle: "El anfitrión se ha ido",
            hostLeftDescription: "El anfitrión se desconectó y el lobby se ha cerrado.",
            create: "Crear",
            join: "Unirse",
            languageLabel: "Idioma",
        },
        create: {
            locationDenied: 'Se denegó el acceso a la ubicación. Para volver a habilitarlo, ve a Ajustes de Safari → Sitios web → Ubicación, busca localhost y configúralo en "Permitir". Luego recarga la página.',
            locationUnavailable: "La información de ubicación no está disponible. Inténtalo de nuevo.",
            locationTimeout: "La solicitud de ubicación caducó. Inténtalo de nuevo.",
            geolocationNotSupported: "Tu navegador no admite la geolocalización",
            title: "crear",
            description: "Ingresa tu nombre para que otros lo vean",
            selectAvatarTitle: "Seleccionar avatar",
            selectAvatarDescription: "Elige un avatar para que otros lo vean",
            avatarOptional: "Selecciona un avatar si lo deseas...",
            nameLabel: "Nombre",
            namePlaceholder: "Neo",
            createButton: "crear",
        },
        join: {
            title: "unirse",
            description: "Ingresa tu nombre para que otros lo vean y el pin proporcionado por el anfitrión",
            selectAvatarTitle: "Seleccionar avatar",
            selectAvatarDescription: "Elige un avatar para que otros lo vean",
            avatarOptional: "Selecciona un avatar si lo deseas...",
            nameLabel: "Nombre",
            namePlaceholder: "Neo",
            pinLabel: "Pin",
            joinButton: "Unirse al anfitrión",
            errorTitle: "Sala no encontrada",
            errorDescription: "El código de sala no es válido o la partida ya finalizó. Revisa el código e inténtalo de nuevo.",
        },
        lobby: {
            start: "Comenzar",
            waitingForHost: "Esperando a que el anfitrión comience...",
            roomPin: "PIN DE SALA",
            loading: "Cargando...",
            players: "JUGADORES",
            joined: "unidos",
            playerFallback: "Jugador",
            newHostTitle: "Nuevo anfitrión",
            newHostDescription: (name) => `${name} ahora es el anfitrión.`,
            pinCopiedTitle: "PIN copiado",
            pinCopiedDescription: "El PIN del lobby se ha copiado al portapapeles.",
            errorTitle: "Error",
            errorCopyDescription: "No se pudo copiar el PIN al portapapeles. Inténtalo de nuevo.",
            hostBadge: "Anfitrión",
            copyPinLabel: "Copiar PIN de sala",
            kickPlayerLabel: (name) => `Expulsar a ${name}`,
        },
        questions: {
            newHostTitle: "Nuevo anfitrión",
            newHostDescription: (name) => `${name} ahora es el anfitrión.`,
            questionOf: (current, total) => `Pregunta ${current} de ${total}`,
            watchingBanner: "👀 Estás observando — la votación está bloqueada para los jugadores originales",
            vote: "Votar",
            voted: "Votado",
        },
        poll: {
            1: {
                question: "¿Cuál es tu principal prioridad para la comida?",
                options: { 1: "Ambiente", 2: "Presupuesto", 3: "Cocina", 4: "Distancia" },
            },
            2: {
                question: "¿Cuál es tu rango de precio preferido?",
                options: { 1: "$", 2: "$$", 3: "$$$", 4: "$$$$" },
            },
            3: {
                question: "¿Qué tipo de cocina se te antoja?",
                options: { 1: "Italiana", 2: "Mexicana", 3: "China", 4: "Japonesa", 5: "Mediterránea", 6: "Americana", 7: "Francesa", 8: "Tailandesa" },
            },
            4: {
                question: "¿Qué tan lejos estás dispuesto a viajar?",
                options: { 1: "A pie (0-1 millas)", 2: "Viaje corto (1-5 millas)", 3: "Viaje moderado (5-15 millas)", 4: "Viaje largo (15+ millas)" },
            },
        },
        results: {
            radiusWalking: "A pie (0-1 millas)",
            radiusShortDrive: "Viaje corto (1-5 millas)",
            radiusModerateDrive: "Viaje moderado (5-15 millas)",
            radiusLongDrive: "Viaje largo (15+ millas)",
            youAreHere: "Estás aquí",
            newHostTitle: "Nuevo anfitrión",
            newHostDescription: (name) => `${name} ahora es el anfitrión.`,
            watching: "👀 Observando",
            broadenedSearchText: "Ampliamos el área de búsqueda para encontrar más opciones",
            broadenedSearchRadius: (label) => ` (ahora buscando dentro de ${label})`,
            votedSuffix: "votaron",
            goingTo: "Vamos a...",
            openNow: "Abierto ahora",
            closed: "Cerrado",
            viewOnGoogleMaps: "Ver en Google Maps",
            exit: "Salir",
            exitVotingPlayerMessage: "¿Salir del juego? Serás eliminado y los demás continuarán votando sin ti.",
            exitVotingHostMessage: "¿Salir como anfitrión? Otro jugador asumirá el control y la votación continuará. Si eres el único jugador, esto terminará el juego.",
            yourVote: "✓ Tu voto",
            alreadyVoted: "Ya votaste",
            voteForThis: "Votar por este",
            votedCheck: "✓ Votado",
            tieBreakTitle: "¡Es un empate!",
            tieBreakSubtitle: "Girando para desempatar...",
            tieBreakWinnerLabel: "La elección está clara:",
        },
        leaveGuard: {
            playerLeaveMessage: "¿Salir del juego? Serás eliminado y los demás continuarán sin ti.",
            hostLeaveMessage: "¿Salir como anfitrión? Otro jugador asumirá el control y el juego continuará. Si eres el único jugador, esto terminará el juego.",
        },
    },
    fr: {
        home: {
            kickedTitle: "Exclu du lobby",
            kickedDescription: "L'hôte vous a retiré du lobby.",
            hostLeftTitle: "L'hôte est parti",
            hostLeftDescription: "L'hôte s'est déconnecté et le lobby a été fermé.",
            create: "Créer",
            join: "Rejoindre",
            languageLabel: "Langue",
        },
        create: {
            locationDenied: 'L\'accès à la localisation a été refusé. Pour le réactiver, allez dans Réglages Safari → Sites web → Localisation, recherchez localhost et réglez-le sur "Autoriser". Puis rechargez la page.',
            locationUnavailable: "Les informations de localisation ne sont pas disponibles. Veuillez réessayer.",
            locationTimeout: "La demande de localisation a expiré. Veuillez réessayer.",
            geolocationNotSupported: "La géolocalisation n'est pas prise en charge par votre navigateur",
            title: "créer",
            description: "Entrez votre nom ci-dessous pour qu'il soit affiché aux autres",
            selectAvatarTitle: "Choisir un avatar",
            selectAvatarDescription: "Choisissez un avatar à afficher aux autres",
            avatarOptional: "Choisissez un avatar si vous le souhaitez...",
            nameLabel: "Nom",
            namePlaceholder: "Neo",
            createButton: "créer",
        },
        join: {
            title: "rejoindre",
            description: "Entrez votre nom ci-dessous pour qu'il soit affiché aux autres, ainsi que le code fourni par l'hôte",
            selectAvatarTitle: "Choisir un avatar",
            selectAvatarDescription: "Choisissez un avatar à afficher aux autres",
            avatarOptional: "Choisissez un avatar si vous le souhaitez...",
            nameLabel: "Nom",
            namePlaceholder: "Neo",
            pinLabel: "Code",
            joinButton: "Rejoindre l'hôte",
            errorTitle: "Salle introuvable",
            errorDescription: "Le code de la salle est invalide ou la partie est déjà terminée. Vérifiez le code et réessayez.",
        },
        lobby: {
            start: "Démarrer",
            waitingForHost: "En attente que l'hôte démarre...",
            roomPin: "CODE DE SALLE",
            loading: "Chargement...",
            players: "JOUEURS",
            joined: "rejoint(s)",
            playerFallback: "Joueur",
            newHostTitle: "Nouvel hôte",
            newHostDescription: (name) => `${name} est maintenant l'hôte.`,
            pinCopiedTitle: "Code copié",
            pinCopiedDescription: "Le code du lobby a été copié dans le presse-papiers.",
            errorTitle: "Erreur",
            errorCopyDescription: "Échec de la copie du code dans le presse-papiers. Réessayez.",
            hostBadge: "Hôte",
            copyPinLabel: "Copier le code de la salle",
            kickPlayerLabel: (name) => `Exclure ${name}`,
        },
        questions: {
            newHostTitle: "Nouvel hôte",
            newHostDescription: (name) => `${name} est maintenant l'hôte.`,
            questionOf: (current, total) => `Question ${current} sur ${total}`,
            watchingBanner: "👀 Vous observez — le vote est réservé aux joueurs d'origine",
            vote: "Voter",
            voted: "Voté",
        },
        poll: {
            1: {
                question: "Quelle est votre priorité principale pour le repas ?",
                options: { 1: "Ambiance", 2: "Budget", 3: "Cuisine", 4: "Distance" },
            },
            2: {
                question: "Quelle est votre gamme de prix préférée ?",
                options: { 1: "$", 2: "$$", 3: "$$$", 4: "$$$$" },
            },
            3: {
                question: "Quel type de cuisine vous tente ?",
                options: { 1: "Italienne", 2: "Mexicaine", 3: "Chinoise", 4: "Japonaise", 5: "Méditerranéenne", 6: "Américaine", 7: "Française", 8: "Thaïlandaise" },
            },
            4: {
                question: "Jusqu'où êtes-vous prêt à voyager ?",
                options: { 1: "À pied (0-1 miles)", 2: "Court trajet (1-5 miles)", 3: "Trajet modéré (5-15 miles)", 4: "Long trajet (15+ miles)" },
            },
        },
        results: {
            radiusWalking: "À pied (0-1 miles)",
            radiusShortDrive: "Court trajet (1-5 miles)",
            radiusModerateDrive: "Trajet modéré (5-15 miles)",
            radiusLongDrive: "Long trajet (15+ miles)",
            youAreHere: "Vous êtes ici",
            newHostTitle: "Nouvel hôte",
            newHostDescription: (name) => `${name} est maintenant l'hôte.`,
            watching: "👀 Observation",
            broadenedSearchText: "Nous avons élargi la zone de recherche pour trouver plus d'options",
            broadenedSearchRadius: (label) => ` (recherche maintenant dans un rayon de ${label})`,
            votedSuffix: "ont voté",
            goingTo: "Nous allons à...",
            openNow: "Ouvert maintenant",
            closed: "Fermé",
            viewOnGoogleMaps: "Voir sur Google Maps",
            exit: "Quitter",
            exitVotingPlayerMessage: "Quitter la partie ? Vous serez retiré et les autres continueront à voter sans vous.",
            exitVotingHostMessage: "Quitter en tant qu'hôte ? Un autre joueur prendra le relais et le vote continuera. Si vous êtes le seul joueur, cela mettra fin à la partie.",
            yourVote: "✓ Votre vote",
            alreadyVoted: "Déjà voté",
            voteForThis: "Voter pour celui-ci",
            votedCheck: "✓ Voté",
            tieBreakTitle: "C'est une égalité !",
            tieBreakSubtitle: "Tirage au sort en cours...",
            tieBreakWinnerLabel: "Le choix est clair :",
        },
        leaveGuard: {
            playerLeaveMessage: "Quitter la partie ? Vous serez retiré et les autres continueront sans vous.",
            hostLeaveMessage: "Quitter en tant qu'hôte ? Un autre joueur prendra le relais et la partie continuera. Si vous êtes le seul joueur, cela mettra fin à la partie.",
        },
    },
    it: {
        home: {
            kickedTitle: "Espulso dalla lobby",
            kickedDescription: "L'host ti ha rimosso dalla lobby.",
            hostLeftTitle: "L'host se n'è andato",
            hostLeftDescription: "L'host si è disconnesso e la lobby è stata chiusa.",
            create: "Crea",
            join: "Unisciti",
            languageLabel: "Lingua",
        },
        create: {
            locationDenied: 'L\'accesso alla posizione è stato negato. Per riabilitarlo, vai su Impostazioni Safari → Siti web → Posizione, trova localhost e impostalo su "Consenti". Poi ricarica la pagina.',
            locationUnavailable: "Le informazioni sulla posizione non sono disponibili. Riprova.",
            locationTimeout: "Richiesta di posizione scaduta. Riprova.",
            geolocationNotSupported: "La geolocalizzazione non è supportata dal tuo browser",
            title: "crea",
            description: "Inserisci il tuo nome per mostrarlo agli altri",
            selectAvatarTitle: "Seleziona avatar",
            selectAvatarDescription: "Scegli un avatar da mostrare agli altri",
            avatarOptional: "Seleziona un avatar se lo desideri...",
            nameLabel: "Nome",
            namePlaceholder: "Neo",
            createButton: "crea",
        },
        join: {
            title: "unisciti",
            description: "Inserisci il tuo nome per mostrarlo agli altri e il pin fornito dall'host",
            selectAvatarTitle: "Seleziona avatar",
            selectAvatarDescription: "Scegli un avatar da mostrare agli altri",
            avatarOptional: "Seleziona un avatar se lo desideri...",
            nameLabel: "Nome",
            namePlaceholder: "Neo",
            pinLabel: "Pin",
            joinButton: "Unisciti all'host",
            errorTitle: "Stanza non trovata",
            errorDescription: "Il codice della stanza non è valido o la partita è già terminata. Controlla il codice e riprova.",
        },
        lobby: {
            start: "Inizia",
            waitingForHost: "In attesa che l'host inizi...",
            roomPin: "PIN STANZA",
            loading: "Caricamento...",
            players: "GIOCATORI",
            joined: "uniti",
            playerFallback: "Giocatore",
            newHostTitle: "Nuovo host",
            newHostDescription: (name) => `${name} è ora l'host.`,
            pinCopiedTitle: "PIN copiato",
            pinCopiedDescription: "Il PIN della lobby è stato copiato negli appunti.",
            errorTitle: "Errore",
            errorCopyDescription: "Impossibile copiare il PIN negli appunti. Riprova.",
            hostBadge: "Host",
            copyPinLabel: "Copia PIN della stanza",
            kickPlayerLabel: (name) => `Espelli ${name}`,
        },
        questions: {
            newHostTitle: "Nuovo host",
            newHostDescription: (name) => `${name} è ora l'host.`,
            questionOf: (current, total) => `Domanda ${current} di ${total}`,
            watchingBanner: "👀 Stai osservando — il voto è bloccato ai giocatori originali",
            vote: "Vota",
            voted: "Votato",
        },
        poll: {
            1: {
                question: "Qual è la tua priorità principale per il pasto?",
                options: { 1: "Ambiente", 2: "Budget", 3: "Cucina", 4: "Distanza" },
            },
            2: {
                question: "Qual è la tua fascia di prezzo preferita?",
                options: { 1: "$", 2: "$$", 3: "$$$", 4: "$$$$" },
            },
            3: {
                question: "Che tipo di cucina desideri?",
                options: { 1: "Italiana", 2: "Messicana", 3: "Cinese", 4: "Giapponese", 5: "Mediterranea", 6: "Americana", 7: "Francese", 8: "Tailandese" },
            },
            4: {
                question: "Fino a che distanza sei disposto a viaggiare?",
                options: { 1: "A piedi (0-1 miglia)", 2: "Breve tragitto (1-5 miglia)", 3: "Tragitto moderato (5-15 miglia)", 4: "Lungo tragitto (15+ miglia)" },
            },
        },
        results: {
            radiusWalking: "A piedi (0-1 miglia)",
            radiusShortDrive: "Breve tragitto (1-5 miglia)",
            radiusModerateDrive: "Tragitto moderato (5-15 miglia)",
            radiusLongDrive: "Lungo tragitto (15+ miglia)",
            youAreHere: "Sei qui",
            newHostTitle: "Nuovo host",
            newHostDescription: (name) => `${name} è ora l'host.`,
            watching: "👀 In osservazione",
            broadenedSearchText: "Abbiamo ampliato l'area di ricerca per trovare più opzioni",
            broadenedSearchRadius: (label) => ` (ora si cerca entro ${label})`,
            votedSuffix: "hanno votato",
            goingTo: "Andiamo a...",
            openNow: "Aperto ora",
            closed: "Chiuso",
            viewOnGoogleMaps: "Vedi su Google Maps",
            exit: "Esci",
            exitVotingPlayerMessage: "Uscire dalla partita? Verrai rimosso e gli altri continueranno a votare senza di te.",
            exitVotingHostMessage: "Uscire come host? Un altro giocatore prenderà il controllo e la votazione continuerà. Se sei l'unico giocatore, la partita terminerà.",
            yourVote: "✓ Il tuo voto",
            alreadyVoted: "Già votato",
            voteForThis: "Vota per questo",
            votedCheck: "✓ Votato",
            tieBreakTitle: "È un pareggio!",
            tieBreakSubtitle: "Sorteggio in corso...",
            tieBreakWinnerLabel: "La scelta è chiara:",
        },
        leaveGuard: {
            playerLeaveMessage: "Uscire dalla partita? Verrai rimosso e gli altri continueranno senza di te.",
            hostLeaveMessage: "Uscire come host? Un altro giocatore prenderà il controllo e la partita continuerà. Se sei l'unico giocatore, la partita terminerà.",
        },
    },
    pt: {
        home: {
            kickedTitle: "Expulso do lobby",
            kickedDescription: "O anfitrião removeu você do lobby.",
            hostLeftTitle: "O anfitrião saiu",
            hostLeftDescription: "O anfitrião desconectou e o lobby foi fechado.",
            create: "Criar",
            join: "Entrar",
            languageLabel: "Idioma",
        },
        create: {
            locationDenied: 'O acesso à localização foi negado. Para reativá-lo, vá em Ajustes do Safari → Sites → Localização, procure localhost e defina como "Permitir". Depois recarregue a página.',
            locationUnavailable: "As informações de localização não estão disponíveis. Tente novamente.",
            locationTimeout: "A solicitação de localização expirou. Tente novamente.",
            geolocationNotSupported: "A geolocalização não é compatível com seu navegador",
            title: "criar",
            description: "Digite seu nome abaixo para ser exibido aos outros",
            selectAvatarTitle: "Selecionar avatar",
            selectAvatarDescription: "Escolha um avatar para ser visto pelos outros",
            avatarOptional: "Selecione um avatar se quiser...",
            nameLabel: "Nome",
            namePlaceholder: "Neo",
            createButton: "criar",
        },
        join: {
            title: "entrar",
            description: "Digite seu nome abaixo para ser exibido aos outros e o pin fornecido pelo anfitrião",
            selectAvatarTitle: "Selecionar avatar",
            selectAvatarDescription: "Escolha um avatar para ser visto pelos outros",
            avatarOptional: "Selecione um avatar se quiser...",
            nameLabel: "Nome",
            namePlaceholder: "Neo",
            pinLabel: "Pin",
            joinButton: "Entrar no anfitrião",
            errorTitle: "Sala não encontrada",
            errorDescription: "O código da sala é inválido ou o jogo já terminou. Verifique o código e tente novamente.",
        },
        lobby: {
            start: "Iniciar",
            waitingForHost: "Aguardando o anfitrião iniciar...",
            roomPin: "PIN DA SALA",
            loading: "Carregando...",
            players: "JOGADORES",
            joined: "entraram",
            playerFallback: "Jogador",
            newHostTitle: "Novo anfitrião",
            newHostDescription: (name) => `${name} agora é o anfitrião.`,
            pinCopiedTitle: "PIN copiado",
            pinCopiedDescription: "O PIN do lobby foi copiado para a área de transferência.",
            errorTitle: "Erro",
            errorCopyDescription: "Falha ao copiar o PIN para a área de transferência. Tente novamente.",
            hostBadge: "Anfitrião",
            copyPinLabel: "Copiar PIN da sala",
            kickPlayerLabel: (name) => `Expulsar ${name}`,
        },
        questions: {
            newHostTitle: "Novo anfitrião",
            newHostDescription: (name) => `${name} agora é o anfitrião.`,
            questionOf: (current, total) => `Pergunta ${current} de ${total}`,
            watchingBanner: "👀 Você está observando — a votação está bloqueada para os jogadores originais",
            vote: "Votar",
            voted: "Votado",
        },
        poll: {
            1: {
                question: "Qual é a sua principal prioridade para a refeição?",
                options: { 1: "Ambiente", 2: "Orçamento", 3: "Culinária", 4: "Distância" },
            },
            2: {
                question: "Qual é a sua faixa de preço preferida?",
                options: { 1: "$", 2: "$$", 3: "$$$", 4: "$$$$" },
            },
            3: {
                question: "Que tipo de culinária você quer?",
                options: { 1: "Italiana", 2: "Mexicana", 3: "Chinesa", 4: "Japonesa", 5: "Mediterrânea", 6: "Americana", 7: "Francesa", 8: "Tailandesa" },
            },
            4: {
                question: "Até onde você está disposto a viajar?",
                options: { 1: "A pé (0-1 milhas)", 2: "Viagem curta (1-5 milhas)", 3: "Viagem moderada (5-15 milhas)", 4: "Viagem longa (15+ milhas)" },
            },
        },
        results: {
            radiusWalking: "A pé (0-1 milhas)",
            radiusShortDrive: "Viagem curta (1-5 milhas)",
            radiusModerateDrive: "Viagem moderada (5-15 milhas)",
            radiusLongDrive: "Viagem longa (15+ milhas)",
            youAreHere: "Você está aqui",
            newHostTitle: "Novo anfitrião",
            newHostDescription: (name) => `${name} agora é o anfitrião.`,
            watching: "👀 Observando",
            broadenedSearchText: "Ampliamos a área de busca para encontrar mais opções",
            broadenedSearchRadius: (label) => ` (agora buscando dentro de ${label})`,
            votedSuffix: "votaram",
            goingTo: "Vamos para...",
            openNow: "Aberto agora",
            closed: "Fechado",
            viewOnGoogleMaps: "Ver no Google Maps",
            exit: "Sair",
            exitVotingPlayerMessage: "Sair do jogo? Você será removido e os outros continuarão votando sem você.",
            exitVotingHostMessage: "Sair como anfitrião? Outro jogador assumirá e a votação continuará. Se você for o único jogador, isso encerrará o jogo.",
            yourVote: "✓ Seu voto",
            alreadyVoted: "Já votou",
            voteForThis: "Votar neste",
            votedCheck: "✓ Votado",
            tieBreakTitle: "Empate!",
            tieBreakSubtitle: "Sorteando para desempatar...",
            tieBreakWinnerLabel: "A escolha é clara:",
        },
        leaveGuard: {
            playerLeaveMessage: "Sair do jogo? Você será removido e os outros continuarão sem você.",
            hostLeaveMessage: "Sair como anfitrião? Outro jogador assumirá e o jogo continuará. Se você for o único jogador, isso encerrará o jogo.",
        },
    },
    ru: {
        home: {
            kickedTitle: "Вы удалены из лобби",
            kickedDescription: "Хост удалил вас из лобби.",
            hostLeftTitle: "Хост покинул игру",
            hostLeftDescription: "Хост отключился, и лобби было закрыто.",
            create: "Создать",
            join: "Войти",
            languageLabel: "Язык",
        },
        create: {
            locationDenied: 'Доступ к геолокации был запрещён. Чтобы снова включить его, перейдите в Настройки Safari → Веб-сайты → Геолокация, найдите localhost и установите значение "Разрешить". Затем перезагрузите страницу.',
            locationUnavailable: "Информация о местоположении недоступна. Попробуйте снова.",
            locationTimeout: "Истекло время ожидания запроса местоположения. Попробуйте снова.",
            geolocationNotSupported: "Ваш браузер не поддерживает геолокацию",
            title: "создать",
            description: "Введите своё имя, чтобы другие могли его видеть",
            selectAvatarTitle: "Выберите аватар",
            selectAvatarDescription: "Выберите аватар, который увидят другие",
            avatarOptional: "Выберите аватар, если хотите...",
            nameLabel: "Имя",
            namePlaceholder: "Нео",
            createButton: "создать",
        },
        join: {
            title: "войти",
            description: "Введите своё имя, чтобы другие могли его видеть, и пин-код, предоставленный хостом",
            selectAvatarTitle: "Выберите аватар",
            selectAvatarDescription: "Выберите аватар, который увидят другие",
            avatarOptional: "Выберите аватар, если хотите...",
            nameLabel: "Имя",
            namePlaceholder: "Нео",
            pinLabel: "Пин-код",
            joinButton: "Присоединиться к хосту",
            errorTitle: "Лобби не найдено",
            errorDescription: "Код лобби неверен или игра уже завершена. Проверьте код и попробуйте снова.",
        },
        lobby: {
            start: "Начать",
            waitingForHost: "Ожидание начала игры хостом...",
            roomPin: "PIN КОМНАТЫ",
            loading: "Загрузка...",
            players: "ИГРОКИ",
            joined: "присоединились",
            playerFallback: "Игрок",
            newHostTitle: "Новый хост",
            newHostDescription: (name) => `${name} теперь хост.`,
            pinCopiedTitle: "PIN скопирован",
            pinCopiedDescription: "PIN лобби скопирован в буфер обмена.",
            errorTitle: "Ошибка",
            errorCopyDescription: "Не удалось скопировать PIN в буфер обмена. Попробуйте снова.",
            hostBadge: "Хост",
            copyPinLabel: "Скопировать PIN комнаты",
            kickPlayerLabel: (name) => `Исключить ${name}`,
        },
        questions: {
            newHostTitle: "Новый хост",
            newHostDescription: (name) => `${name} теперь хост.`,
            questionOf: (current, total) => `Вопрос ${current} из ${total}`,
            watchingBanner: "👀 Вы наблюдаете — голосование доступно только исходным игрокам",
            vote: "Голосовать",
            voted: "Проголосовано",
        },
        poll: {
            1: {
                question: "Что для вас сейчас важнее всего в еде?",
                options: { 1: "Атмосфера", 2: "Бюджет", 3: "Кухня", 4: "Расстояние" },
            },
            2: {
                question: "Какой ценовой диапазон вы предпочитаете?",
                options: { 1: "$", 2: "$$", 3: "$$$", 4: "$$$$" },
            },
            3: {
                question: "Какую кухню вам хочется попробовать?",
                options: { 1: "Итальянская", 2: "Мексиканская", 3: "Китайская", 4: "Японская", 5: "Средиземноморская", 6: "Американская", 7: "Французская", 8: "Тайская" },
            },
            4: {
                question: "Как далеко вы готовы поехать?",
                options: { 1: "Пешком (0-1 миля)", 2: "Короткая поездка (1-5 миль)", 3: "Средняя поездка (5-15 миль)", 4: "Длинная поездка (15+ миль)" },
            },
        },
        results: {
            radiusWalking: "Пешком (0-1 миля)",
            radiusShortDrive: "Короткая поездка (1-5 миль)",
            radiusModerateDrive: "Средняя поездка (5-15 миль)",
            radiusLongDrive: "Длинная поездка (15+ миль)",
            youAreHere: "Вы здесь",
            newHostTitle: "Новый хост",
            newHostDescription: (name) => `${name} теперь хост.`,
            watching: "👀 Наблюдение",
            broadenedSearchText: "Мы расширили область поиска, чтобы найти больше вариантов",
            broadenedSearchRadius: (label) => ` (теперь поиск в пределах ${label})`,
            votedSuffix: "проголосовали",
            goingTo: "Мы идём в...",
            openNow: "Открыто сейчас",
            closed: "Закрыто",
            viewOnGoogleMaps: "Посмотреть на Google Maps",
            exit: "Выход",
            exitVotingPlayerMessage: "Покинуть игру? Вы будете удалены, а остальные продолжат голосование без вас.",
            exitVotingHostMessage: "Покинуть игру как хост? Другой игрок возьмёт на себя управление, и голосование продолжится. Если вы единственный игрок, игра завершится.",
            yourVote: "✓ Ваш голос",
            alreadyVoted: "Уже проголосовали",
            voteForThis: "Голосовать за это",
            votedCheck: "✓ Голос учтён",
            tieBreakTitle: "Ничья!",
            tieBreakSubtitle: "Определяем победителя...",
            tieBreakWinnerLabel: "Выбор очевиден:",
        },
        leaveGuard: {
            playerLeaveMessage: "Покинуть игру? Вы будете удалены, а остальные продолжат без вас.",
            hostLeaveMessage: "Покинуть игру как хост? Другой игрок возьмёт на себя управление, и игра продолжится. Если вы единственный игрок, игра завершится.",
        },
    },
};

export const SUPPORTED_LANGUAGES = ['en', 'es', 'fr', 'it', 'pt', 'ru'];

export const DEFAULT_LANGUAGE = 'en';
